name: ds_collection
description: Deadly simple collection extension
version: 1.0.0
repository: https://github.com/uac-nhan-nguyen/ds_collection
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.22.1
  collection: ^1.17.0

